from typing import List, Dict, Any
from schemas.agent_outputs import (
    CodeReaderOutput, BugDetectorOutput, TestSuggesterOutput, DocWriterOutput
)

severity_emoji = {
    "critical": "🔴",
    "high": "🟠",
    "warning": "🟡",
    "medium": "🟡",
    "suggestion": "🔵",
    "low": "🔵",
}

SEVERITY_WEIGHTS = {
    "critical": 1.0,
    "high": 0.75,
    "warning": 0.6,
    "medium": 0.5,
    "suggestion": 0.3,
    "low": 0.25,
}


def normalize_severity(sev: str) -> str:
    s = sev.lower()
    return s if s in SEVERITY_WEIGHTS else "medium"


def format_github_comment(
    code: CodeReaderOutput,
    bugs: BugDetectorOutput,
    tests: TestSuggesterOutput,
    docs: DocWriterOutput,
    consensus_findings: List[Dict[str, Any]] | None = None,
) -> str:
    """
    If consensus_findings is provided, use them as the primary source of findings.
    Otherwise, fall back to the original bugs.findings.
    """
    lines = [
        "## 🤖 AI PR Review",
        f"> **Risk score:** {bugs.overall_risk_score:.1f}/10 · **Complexity:** {code.complexity_estimate} · **Language:** {code.language}",
        "",
        "### Summary",
        code.overall_summary,
        "",
    ]

    # Use consensus findings if available
    findings = []
    if consensus_findings:
        for cf in consensus_findings:
            findings.append({
                "severity": cf.get("severity", "medium"),
                "filename": cf.get("file_path", "unknown"),
                "line_hint": f"lines {cf.get('line_start', '?')}-{cf.get('line_end', '?')}"
                if cf.get("line_start") is not None
                else "",
                "description": cf.get("description", ""),
                "fix_suggestion": cf.get("fix_suggestion", "Review and fix as appropriate."),
                "agreeing_agents": cf.get("agreeing_agents", []),
            })
    else:
        for f in bugs.findings:
            findings.append({
                "severity": f.severity,
                "filename": f.filename,
                "line_hint": f.line_hint,
                "description": f.description,
                "fix_suggestion": f.fix_suggestion,
                "agreeing_agents": [f.agent_name] if hasattr(f, "agent_name") else [],
            })

    if findings:
        lines += ["### Findings", ""]
        for f in findings:
            emoji = severity_emoji.get(normalize_severity(f["severity"]), "⚪")
            agents_tag = ""
            if f.get("agreeing_agents"):
                agents_tag = f" · Agreed by: {', '.join(f['agreeing_agents'])}"
            lines.append(f"{emoji} **{f['severity'].upper()}** — `{f['filename']}` ({f['line_hint']}){agents_tag}")
            lines.append(f"  {f['description']}")
            lines.append(f"  > Fix: {f['fix_suggestion']}")
            lines.append("")
    else:
        lines += ["### Findings", "✅ No issues found.", ""]

    if tests.suggested_tests:
        lines += ["### Suggested Tests", ""]
        for t in tests.suggested_tests[:3]:
            lines.append(f"- **`{t.function_name}`** — {t.test_description}")
        lines.append("")

    if docs.improvements:
        lines += [f"### Docs ({docs.missing_docs_count} missing/outdated)", ""]
        for d in docs.improvements[:3]:
            lines.append(f"- `{d.filename}` → `{d.function_name}`")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by PR Agent*")
    return "\n".join(lines)


def compute_risk_score(bugs: BugDetectorOutput) -> float:
    return bugs.overall_risk_score


def compute_consensus_risk_score(consensus_findings: List[Dict[str, Any]]) -> float:
    """
    Compute a 0–10 risk score from consensus findings.
    Higher severity + higher consensus → higher risk.
    """
    if not consensus_findings:
        return 0.0

    total_weight = 0.0
    weighted_sum = 0.0

    for cf in consensus_findings:
        sev = normalize_severity(cf.get("severity", "medium"))
        w = SEVERITY_WEIGHTS.get(sev, 0.5)
        consensus = float(cf.get("consensus_score", 0.5))
        total_weight += w
        weighted_sum += w * consensus

    if total_weight == 0:
        return 0.0

    # Map 0–1 score to 0–10
    normalized = weighted_sum / total_weight
    return round(normalized * 10, 2)